name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # O la rama desde la que quieres desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f namespace.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f hpc-cluster-deployment.yaml
        kubectl apply -f hpc-cluster-service.yaml

    - name: Verify deployment
      run: kubectl get all -n hpc-project
