apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-server
  labels:
    app: flask-server
spec:
  replicas: 3  # Número de réplicas para alta disponibilidad
  selector:
    matchLabels:
      app: flask-server
  template:
    metadata:
      labels:
        app: flask-server
    spec:
      containers:
      - name: flask-server
        image: tu_usuario/flask-server:latest  # Imagen Docker del servidor Flask
        ports:
        - containerPort: 5000
        env:
        - name: HPC_CLUSTER_URL
          value: "http://hpc-cluster-service:8080"  # URL del servicio del clúster
