apiVersion: v1
kind: Service
metadata:
  name: flask-server-service
spec:
  selector:
    app: flask-server
  ports:
  - protocol: TCP
    port: 80  # Puerto expuesto
    targetPort: 5000  # Puerto del contenedor
  type: LoadBalancer  # Exponer el servicio fuera del clúster
